AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6

  Include:
    - '**/Rakefile'
    - '**/config.ru'

  Exclude:
    - 'db/schema.rb'

Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/SymbolArray:
  Enabled: true

Style/LambdaCall:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/LineLength:
  Max: 140

Metrics/BlockLength:
  Exclude:
    - 'tasks/**/*.rake'
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'
    - 'spec/support/**/*.rb'
