AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6

  Include:
    - '**/*/*.rb'
    - '**/Rakefile'
    - '**/config.ru'

  Exclude:
    - 'db/schema.rb'

Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/Debugger:
  Exclude:
    - 'prototype.rb'

Style/SymbolArray:
  Enabled: true

Style/LambdaCall:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Max: 140

Metrics/BlockLength:
  Exclude:
    - 'tasks/**/*.rake'
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'
    - 'spec/support/**/*.rb'

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required
