version: '3'

services:
  app:
    build: .
    command: bin/server
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/ecb-exchange_production
    ports:
      - 9292:9292
    depends_on:
      - postgres

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecb-exchange_production
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata:
