# frozen_string_literal: true

namespace :db do
  ENVIRONMENT = ENV['RACK_ENV'] || 'development'

  task :_setup do
    DB.loggers.clear # Disable annoying logging Sequel commands into the console

    Sequel.extension :migration
  end

  desc 'Run database migrations'
  task :migrate, %i[version] => %i[_setup] do |_, args|
    puts "Migrating to latest for: #{ENVIRONMENT}"

    version = args[:version] if args[:version]

    Sequel::Migrator.run(DB, 'db/migrations', target: version)

    # Don't dump DB schema while migrating in any environment but development
    Rake::Task['db:schema'].execute if ENVIRONMENT == 'development'
  end

  desc 'Reset migrations (full rollback and migration)'
  task reset: %i[_setup] do
    puts "Rolling back #{ENVIRONMENT} database"

    Sequel::Migrator.run(DB, 'db/migrations', target: 0)

    Rake::Task['db:migrate'].execute
  end

  desc 'Print out final schema to file'
  task schema: %i[_setup] do
    DB.extension :schema_dumper

    File.open('db/schema.rb', 'w') do |file|
      header = <<~HEADER
        # This schema file is automatically generated by `rake db:schema`.
        # It will be overwritten periodically so do not make changes.
      HEADER

      puts 'Writing schema to db/schema.rb'

      file.write(header)
      file.write(DB.dump_schema_migration)
    end
  end
end
