# frozen_string_literal: true

namespace :db do
  task :_setup do
    Sequel.extension :migration
  end

  desc 'Run database migrations'
  task migrate: %i[_setup] do
    puts "Migrating to latest for: #{ENV['RACK_ENV'] || 'development'}"
    Sequel::Migrator.run(DB, 'db/migrations')
    Rake::Task['db:schema'].execute
  end

  desc 'Reset migrations (full rollback and migration)'
  task reset: %i[_setup] do
    puts "Rolling back #{ENV['RACK_ENV'] || 'development'} database"
    Sequel::Migrator.run(DB, 'db/migrations', target: 0)
    Rake::Task['db:migrate'].execute
  end

  desc 'Print out final schema to file'
  task schema: %i[_setup] do
    DB.extension :schema_dumper
    File.open('db/schema.rb', 'w') do |file|
      header = <<~END
        # This schema file is automatically generated by `rake db:schema`.
        # It will be overwritten periodically so do not make changes.
      END
      puts 'Writing schema to db/schema.rb'
      file.write(header)
      file.write(DB.dump_schema_migration)
    end
  end
end
