# This schema file is automatically generated by `rake db:schema`.
# It will be overwritten periodically so do not make changes.
Sequel.migration do
  change do
    create_table(:exchange_rates) do
      Date :date, :null=>false
      BigDecimal :rate, :size=>[8, 4]
      
      primary_key [:date]
    end
    
    create_table(:schema_info) do
      Integer :version, :default=>0, :null=>false
    end
  end
end
